### ISSUE TITLE
alpi is not in the sudoers file

### ISSUE THREAD

**Issue by vincenzopalazzo** [rootwyrm/alpine-imager#2]
on raspberry pi3 I had the following error

```
localhost:~$ sudo apk update
[sudo] password for alpi: 
alpi is not in the sudoers file.  This incident will be reported.
localhost:~$ 
```

**Comment by rootwyrm** [comment]
Oh my, well that's embarrassing on my part. Give me about an hour. :)

**Comment by vincenzopalazzo** [comment]
Thanks!

Maybe there is also some problem with the root password? I can not access to it

**Comment by rootwyrm** [comment]
This is interesting though. Problematic code:
```
alpine_prep.sh:
	## Add alpi to sudoers
	sed -i -E '/#includedir/ i alpi\tALL=(ALL)\tALL' ${CHROOT}/etc/sudoers
	CHECK_ERROR $? "alpi sudoer"
	printf 'Added alpi to /etc/sudoers\n' | tee -a ${logfile}
```
Somebody went and changed what I was keying off of, and `CHECK_ERROR` didn't catch it because sed said no error. Switched the key, so that's fixed.

root password issue is a bit more difficult; got caught out by an interpretation change on `!`.

**Comment by rootwyrm** [comment]
Bad Github, no close yet!
Going to bump versions as well, but both of those issues should be fixed.

**Comment by rootwyrm** [comment]
OK, both should be fully fixed.
Updated releases to live versions:

- 3.15.4
- 3.14.6
- 3.13.10
- Removed 3.12 (EOS on May 1 2022)
- Removed 3.11 (EOS was November 1 2021)

**Comment by vincenzopalazzo** [comment]
Thanks I will test it tomorrow :)
